collabritive filtering

importing pandas to open files and manupilate data 
pandas is a opensource library
from sklearn importing cosine_similarity

In [1]:

import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [2]:

ratings = pd.read_csv('food_ratings.csv')#opeing food_ratings with pandas
recipes_names = pd.read_csv('all_recipes.csv').drop_duplicates(subset='title') # opening all the recipes and droping duplicated values and titles
recipes_and_ratings = pd.merge(ratings , recipes_names , on='recipe_id')#merging food ratings and recipes

In [3]:
ratings.head()

,date,rating,recipe_id,review,user_id,username
0,2012-09-11,5,222234,This recipe was delicious! Instead of cherry p...,3419993,Pie84
1,2012-12-25,5,222234,Made this recipe as instructed and it was easy...,3154459,hertzen
2,2012-11-22,5,222234,This was a great recipe to make using leftover...,10370475,suziloo
3,2015-07-07,5,222234,"Tasty , simple dessert that comes out cute as ...",2304335,Chelsea M.
4,2016-12-31,5,222234,"Delicious!! I was pressed for time, so I didn'...",1967176,Amanda H.

In [4]:
recipes_names.head()

,calories,category,ingredients,ratings,recipe_id,reviews,title,total_mins
0,728,"['Desserts', 'Fruit Desserts', 'Pineapple Dess...","['2 cups all-purpose flour', '1 teaspoon salt'...",4.703704,263516,23,Chef John's Carrot Cake,95
1,692,"['Bread', 'Yeast Bread']","['1/2 cup warm milk', '1/3 cup warm water', '1...",4.666667,272625,2,Khachapuri (Georgian Cheese Bread),115
2,209,"['Soups, Stews and Chili', 'Stews', 'Beef']","['1 (1 1/2-pound) flank steak', '2 teaspoons k...",5.000000,272615,4,Ropa Vieja (Cuban Beef),690
3,505,"['Everyday Cooking', 'Vegetarian', 'Side Dishes']","['2 cups whole milk', '1 teaspoon kosher salt,...",4.333333,272461,9,"""Instant"" Mac and Cheese",28
4,291,"['Bread', 'Yeast Bread']","['1 cup warm water', '1 tablespoon white sugar...",5.000000,271049,4,Kouign-Amann,275

In [5]:
recipes_and_ratings.head()

,date,rating,recipe_id,review,user_id,username,calories,category,ingredients,ratings,reviews,title,total_mins
0,2012-09-11,5,222234,This recipe was delicious! Instead of cherry p...,3419993,Pie84,275,"['Desserts', 'Pies', 'Tarts', 'Fruit Tarts']","['6 ounces white whole wheat flour', '1 teaspo...",5.0,8,Cherry Folditup,170
1,2012-12-25,5,222234,Made this recipe as instructed and it was easy...,3154459,hertzen,275,"['Desserts', 'Pies', 'Tarts', 'Fruit Tarts']","['6 ounces white whole wheat flour', '1 teaspo...",5.0,8,Cherry Folditup,170
2,2012-11-22,5,222234,This was a great recipe to make using leftover...,10370475,suziloo,275,"['Desserts', 'Pies', 'Tarts', 'Fruit Tarts']","['6 ounces white whole wheat flour', '1 teaspo...",5.0,8,Cherry Folditup,170
3,2015-07-07,5,222234,"Tasty , simple dessert that comes out cute as ...",2304335,Chelsea M.,275,"['Desserts', 'Pies', 'Tarts', 'Fruit Tarts']","['6 ounces white whole wheat flour', '1 teaspo...",5.0,8,Cherry Folditup,170
4,2016-12-31,5,222234,"Delicious!! I was pressed for time, so I didn'...",1967176,Amanda H.,275,"['Desserts', 'Pies', 'Tarts', 'Fruit Tarts']","['6 ounces white whole wheat flour', '1 teaspo...",5.0,8,Cherry Folditup,170

cleaning data with deleting users with less than 4 ratings

In [7]:
better_user_ratings = recipes_and_ratings.pivot_table(index='title',columns='user_id',values='rating')#pivoting tables setting title as index and user_idies as columns
better_user_ratings = better_user_ratings.dropna(thresh=4 , axis=1)#droping nan vlues users with threshold of 4
print(recipes_and_ratings.shape)

better_user_ratings.head()

user_id,39,16873,20839,26598,31529,34237,35406,40369,49190,51226,...,24175906,24388339,24572070,24596470,24697060,24803231,24992909,25340908,25370729,25492240
title,,,,,,,,,,,,,,,,,,,,,
"""Burnt"" Basque Cheesecake",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Code Red"" Cheese Spread",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Instant"" Mac and Cheese",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
"""Naked"" Cherry Tomato Salad",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Special"" Roasted Potatoes",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

replacing new ids with old ids and deleteing ratings with no user id

In [11]:
new_user_list = better_user_ratings.columns.tolist()
recipes_and_ratings = recipes_and_ratings.loc[recipes_and_ratings['user_id'].isin(new_user_list)]
print(recipes_and_ratings.shape)
recipes_and_ratings.head()

(12235, 13)

,date,rating,recipe_id,review,user_id,username,calories,category,ingredients,ratings,reviews,title,total_mins
7,2016-02-22,5,222234,Great recipe. Easy to make but looks impressiv...,9115416,Kari BO'B,275,"['Desserts', 'Pies', 'Tarts', 'Fruit Tarts']","['6 ounces white whole wheat flour', '1 teaspo...",5.000000,8,Cherry Folditup,170
20,2019-01-04,5,263516,"Really good cake, I doubled the frosting with ...",21451454,cooker11,728,"['Desserts', 'Fruit Desserts', 'Pineapple Dess...","['2 cups all-purpose flour', '1 teaspoon salt'...",4.703704,23,Chef John's Carrot Cake,95
24,2018-11-24,5,263516,This cake is excellent! I made it almost exact...,4814450,Foodie,728,"['Desserts', 'Fruit Desserts', 'Pineapple Dess...","['2 cups all-purpose flour', '1 teaspoon salt'...",4.703704,23,Chef John's Carrot Cake,95
27,2018-06-23,5,263516,I THOUGHT THIS WAS DELISH BUT ADDED 1 CUP COCO...,17901819,mary,728,"['Desserts', 'Fruit Desserts', 'Pineapple Dess...","['2 cups all-purpose flour', '1 teaspoon salt'...",4.703704,23,Chef John's Carrot Cake,95
32,2019-05-01,5,272625,It was soooo good.,1543289,Sharon B,692,"['Bread', 'Yeast Bread']","['1/2 cup warm milk', '1/3 cup warm water', '1...",4.666667,2,Khachapuri (Georgian Cheese Bread),115

In [19]:
recipes_titles= recipes_names['title'].str.replace('"','').tolist()#replacing " to empty space for avoiding errors in api

In [12]:
recipes_and_ratings =recipes_and_ratings.pivot_table(index='user_id', columns='title', values='rating')
recipes_and_ratings.head()

title,"""Instant"" Mac and Cheese","""Special"" Roasted Potatoes",12-Second Coleslaw,Affogato with Cold-Brewed Coffee,Airline Chicken Breast,Alabama-Style White Barbecue Sauce,All-American Burger Dog,Almond and Parsley Salsa Verde,Almost Fat-Free Green Onion Potato Salad,Amena's Triple Chocolate Chip Cookies,...,Upside-Down Barbeque Meatloaf,Utica Greens and Beans,Valentine's Salmon,Vanilla Bean Pastry Cream,Veracruz-Style Red Snapper,Walnut and Parsley Pesto,White Bean Chicken Breast Chili,Whole-Grain Blueberry Scones,World's Fastest Meatballs,Zucchini and Ricotta Casserole
user_id,,,,,,,,,,,,,,,,,,,,,
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
recipes_and_ratings = recipes_and_ratings.fillna(0)
recipes_and_ratings.head()

title,"""Instant"" Mac and Cheese","""Special"" Roasted Potatoes",12-Second Coleslaw,Affogato with Cold-Brewed Coffee,Airline Chicken Breast,Alabama-Style White Barbecue Sauce,All-American Burger Dog,Almond and Parsley Salsa Verde,Almost Fat-Free Green Onion Potato Salad,Amena's Triple Chocolate Chip Cookies,...,Upside-Down Barbeque Meatloaf,Utica Greens and Beans,Valentine's Salmon,Vanilla Bean Pastry Cream,Veracruz-Style Red Snapper,Walnut and Parsley Pesto,White Bean Chicken Breast Chili,Whole-Grain Blueberry Scones,World's Fastest Meatballs,Zucchini and Ricotta Casserole
user_id,,,,,,,,,,,,,,,,,,,,,
39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16873,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20839,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26598,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31529,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
def standarize(row):
    new_row = (row -row.mean()) / (row.max()-row.min())
    return new_row
recipes_and_ratings = recipes_and_ratings.apply(standarize)
recipes_and_ratings.head()

title,"""Instant"" Mac and Cheese","""Special"" Roasted Potatoes",12-Second Coleslaw,Affogato with Cold-Brewed Coffee,Airline Chicken Breast,Alabama-Style White Barbecue Sauce,All-American Burger Dog,Almond and Parsley Salsa Verde,Almost Fat-Free Green Onion Potato Salad,Amena's Triple Chocolate Chip Cookies,...,Upside-Down Barbeque Meatloaf,Utica Greens and Beans,Valentine's Salmon,Vanilla Bean Pastry Cream,Veracruz-Style Red Snapper,Walnut and Parsley Pesto,White Bean Chicken Breast Chili,Whole-Grain Blueberry Scones,World's Fastest Meatballs,Zucchini and Ricotta Casserole
user_id,,,,,,,,,,,,,,,,,,,,,
39,-0.001549,-0.0081,-0.002025,-0.002025,-0.001191,-0.002859,-0.002859,-0.000596,-0.001429,-0.007266,...,-0.002501,-0.000596,-0.001072,-0.00274,-0.019178,-0.001191,-0.007266,-0.001787,-0.00274,-0.001191
16873,-0.001549,-0.0081,-0.002025,-0.002025,-0.001191,-0.002859,-0.002859,-0.000596,-0.001429,-0.007266,...,-0.002501,-0.000596,-0.001072,-0.00274,-0.019178,-0.001191,-0.007266,-0.001787,-0.00274,-0.001191
20839,-0.001549,-0.0081,-0.002025,-0.002025,-0.001191,-0.002859,-0.002859,-0.000596,-0.001429,-0.007266,...,-0.002501,-0.000596,-0.001072,-0.00274,-0.019178,-0.001191,-0.007266,-0.001787,-0.00274,-0.001191
26598,-0.001549,-0.0081,-0.002025,-0.002025,-0.001191,-0.002859,-0.002859,-0.000596,-0.001429,-0.007266,...,-0.002501,-0.000596,-0.001072,-0.00274,-0.019178,-0.001191,-0.007266,-0.001787,-0.00274,-0.001191
31529,-0.001549,-0.0081,-0.002025,-0.002025,-0.001191,-0.002859,-0.002859,-0.000596,-0.001429,-0.007266,...,-0.002501,-0.000596,-0.001072,-0.00274,-0.019178,-0.001191,-0.007266,-0.001787,-0.00274,-0.001191

In [16]:
recipes_and_ratings.shape

(1679, 1020)

In [17]:
recipes_and_ratings = recipes_and_ratings.iloc[0:1151,:]

calculating cosine similarity and turning it to a dataframe to be able to save it on disk

In [24]:

item_similarity = cosine_similarity(recipes_and_ratings)
item_similarity = pd.DataFrame(item_similarity,columns=recipes_titles,index=recipes_titles)
item_similarity.head()

,Chef John's Carrot Cake,Khachapuri (Georgian Cheese Bread),Ropa Vieja (Cuban Beef),Instant Mac and Cheese,Kouign-Amann,Mississippi Beef Short Ribs,German Potato Dumplings (Kartoffelkloesse),Chef John's Strawberry Semifreddo,Chicken Parmesan,The Best Parmesan Chicken Bake,...,Bluetons (Blue Cheese Croutons),Whole Chicken Pie,Baked Cauliflower Fries,Layered NorCal Nicoise Salad,Chef John's Waldorf Salad,Bourbon Pepper Pan Sauce,Chef John's Sweet Potato Biscuits,Flax Seed Crackers,Brandade,Folded Pork Cutlets
Chef John's Carrot Cake,1.000000,-0.017069,0.013259,-0.010396,-0.008113,-0.015727,-0.011502,-0.009515,-0.014731,0.050578,...,0.100510,-0.024266,-0.026112,0.109974,0.077818,-0.001864,-0.014111,-0.025038,-0.010235,-0.020638
Khachapuri (Georgian Cheese Bread),-0.017069,1.000000,0.157615,-0.018514,-0.016109,-0.025154,-0.019754,-0.018444,-0.023610,-0.018849,...,-0.027928,-0.035329,-0.039671,-0.015459,0.041352,0.197488,-0.024821,-0.038265,-0.018886,-0.028927
Ropa Vieja (Cuban Beef),0.013259,0.157615,1.000000,-0.035431,-0.036089,-0.039107,-0.035495,-0.040043,0.031375,0.048794,...,-0.040166,-0.042654,0.091815,0.049414,0.042952,-0.032243,-0.046525,-0.053212,-0.038234,0.023061
Instant Mac and Cheese,-0.010396,-0.018514,-0.035431,1.000000,-0.002599,-0.015687,-0.009093,-0.003835,-0.014608,-0.013404,...,-0.019611,-0.030310,-0.029716,-0.001850,-0.029897,0.007670,-0.010127,0.202392,-0.005796,-0.027742
Kouign-Amann,-0.008113,-0.016109,-0.036089,-0.002599,1.000000,-0.012496,-0.005066,0.002121,-0.011558,-0.011790,...,-0.017103,-0.029733,-0.027030,0.003786,-0.031053,0.014832,-0.004454,-0.025240,-0.000578,-0.028649

testing the model

In [26]:
food_name = "Chef John's Carrot Cake"
user_rating = 5
similar_score = item_similarity[food_name]*(user_rating-2.5)
similar_score = similar_score.sort_values(ascending=False)
print(similar_score)

Chef John's Carrot Cake                                                2.500000
Chef John's Ricotta Pie                                                0.648883
Grilled Brie and Pear Sandwich                                         0.635878
Black Onion Relish                                                     0.596503
Pan-Roasted Halibut with Clamshell Mushrooms and Lemon Butter Sauce    0.566830
Chef John's Shrimp Etouffee                                            0.490367
Lamb Braised in Pomegranate                                            0.473357
Chef John's Thai-Style Sweet Chili Sauce                               0.468524
Scallops with Arugula, Lentils, and Butter Beans                       0.394139
Sandwich Rolls                                                         0.383204
Molasses Brined Pork Chops                                             0.363999
Lamb and Rice Stuffed Grape Leaves                                     0.361509
Chef John's Baked Eggplant Sandwiches                                  0.358980
Tuscan Onion Soup (Carabaccia)                                         0.356849
Honey-Brined Fried Chicken Breasts                                     0.356275
Detroit-Style Pizza                                                    0.356243
Chef John's Colcannon Hash                                             0.356110
Savory Buttermilk Meatloaf                                             0.355978
Cotechino and Braised Beans                                            0.350566
Chef John's Pumpkin Seed Brittle                                       0.349965
Poached Pears Belle Helene                                             0.349231
Crostini Dijonnaise                                                    0.345996
Pickled Ginger Asian Pear Coleslaw                                     0.344773
Chef John's Hawaiian-Style Ahi Poke                                    0.335870
Chef John's White Sauce                                                0.331458
Chef John's Chicken Cacciatore                                         0.331283
Chocolate Cream Puff Swans                                             0.329566
Mexican-Style Shrimp Cocktail                                          0.328558
Chef John's Pourable Pizza                                             0.328250
Potato and Chorizo Mini Quiches                                        0.325842
                                                                         ...
Crispy Pork Belly                                                     -0.083414
Asparagus Pie                                                         -0.083545
Feta Roast Chicken                                                    -0.083834
Simple Garlic Shrimp                                                  -0.083894
Truffled Cauliflower Gratin                                           -0.084830
Prawns Provencale                                                     -0.086056
Eastern North Carolina Barbecue Sauce with a West Coast Twist         -0.086141
How to Make Homemade Pizza Sauce                                      -0.086594
Rigatoni alla Genovese                                                -0.086602
Pancetta-Wrapped Leek Gratin                                          -0.087536
Cinco de Mayo Salsa Cruda                                             -0.089006
Chef John's Pumpkin Cinnamon Rolls                                    -0.090374
Chef John's Flour Tortillas                                           -0.091501
Chef John's Chocolate Egg Cream                                       -0.093032
Deviled Lobster Tails                                                 -0.094189
Spicy Orange Zest Beef                                                -0.094382
Chef John's Lighter Lemon Curd                                        -0.094463
Grilled Spanish Mustard Beef                                          -0.095633
Quick Pickled Jalapeno Rings                                          -0.097153
Chef John's Patatas Bravas                                            -0.098793
Chef John's Deviled Eggs                                              -0.100020
Chef John's No-Knead Ciabatta                                         -0.103809
Lemon Ricotta Pancakes                                                -0.103864
Chef John's Grilled Jerk Pork Tenderloin                              -0.104635
Chef John's Homemade Croutons                                         -0.105327
Poutine Gravy                                                         -0.108808
How to Make Tres Leches Cake                                          -0.110445
Pizza with Ham, Asparagus, and Ricotta                                -0.115091
Eggplant Parmesan Casserole                                           -0.128408
Homemade Cheese Curds                                                 -0.128450
Name: Chef John's Carrot Cake, Length: 1151, dtype: float64